apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: voting-app
data:
 enable-scale-to-zero: "false"
spec:
  template:
    spec:
      containers:
        - image: docker.io/diego727/voting-app:v2
          ports:
            - containerPort: 8001
  
