apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: result-app
spec:
  template:
    spec:
      containers:
        - image: docker.io/diego727/result-app:v1
          ports:
            - containerPort: 3000